import type { Vacancy } from './types';

export const demoVacancies: Vacancy[] = [
  {
    id: 'demo-festival-helper',
    title: 'Помощь на семейном фестивале',
    category: 'Помощь на мероприятиях',
    event_date: '2026-08-15',
    start_time: '12:00',
    end_time: '16:00',
    place: 'Центр культуры',
    estimated_minutes: 240,
    slots: 5,
    free_slots: 2,
    min_age: 14,
    max_age: null,
    format: 'Очно',
    confirmation_type: 'Подтверждение организатора',
    confirmation_text: 'Организатор отметит участие и фактически отработанное время.',
    description: 'Помочь встретить участников, подсказать дорогу к площадкам и поддерживать порядок в рабочей зоне.',
    duties: ['Прийти за 20 минут до начала', 'Пройти короткий инструктаж', 'Помогать участникам и организатору'],
    take_with_you: 'Удобную одежду, воду и заряженный телефон.',
    contact_person: 'Евгений Валерьевич Кустов',
    is_active: true
  },
  {
    id: 'demo-media-photo',
    title: 'Фотосъёмка доброго дела',
    category: 'Медиа',
    event_date: '2026-08-18',
    start_time: '14:00',
    end_time: '16:00',
    place: 'Место будет указано после записи',
    estimated_minutes: 120,
    slots: 2,
    free_slots: 1,
    min_age: 12,
    max_age: null,
    format: 'Очно',
    confirmation_type: 'Ссылка на материал',
    confirmation_text: 'Нужно отправить ссылку на папку с фотографиями.',
    description: 'Сделать понятный фотоотчёт: общий план, процесс работы, детали и итоговый результат.',
    duties: ['Снять не менее 15 удачных кадров', 'Не фотографировать людей без разрешения', 'Загрузить материалы в одну папку'],
    take_with_you: 'Телефон или фотоаппарат с заряженной батареей.',
    contact_person: 'Евгений Валерьевич Кустов',
    is_active: true
  },
  {
    id: 'demo-books-help',
    title: 'Помощь при сборе книг',
    category: 'Помощь людям',
    event_date: '2026-08-22',
    start_time: '15:00',
    end_time: '18:00',
    place: 'Кемь, точный адрес в подтверждённой заявке',
    estimated_minutes: 180,
    slots: 6,
    free_slots: 4,
    min_age: 12,
    max_age: null,
    format: 'Очно',
    confirmation_type: 'Подтверждение организатора',
    confirmation_text: 'Организатор подтвердит присутствие и количество часов.',
    description: 'Принять книги, рассортировать их по возрасту читателей и аккуратно упаковать для передачи.',
    duties: ['Принимать книги', 'Сортировать по категориям', 'Подписывать и собирать коробки'],
    take_with_you: 'Ничего специального брать не нужно.',
    contact_person: 'Евгений Валерьевич Кустов',
    is_active: true
  },
  {
    id: 'demo-remote-text',
    title: 'Подготовить текст для доброй акции',
    category: 'Дистанционные задания',
    event_date: '2026-08-25',
    start_time: '18:00',
    end_time: '20:00',
    place: 'Можно выполнить из дома',
    estimated_minutes: 120,
    slots: 3,
    free_slots: 3,
    min_age: 13,
    max_age: null,
    format: 'Дистанционно',
    confirmation_type: 'Ссылка или файл',
    confirmation_text: 'Нужно отправить ссылку на документ с готовым текстом.',
    description: 'Подготовить короткий и понятный текст о предстоящей благотворительной акции по выданным фактам.',
    duties: ['Изучить материалы', 'Написать текст без выдуманных фактов', 'Проверить имена, даты и ссылки'],
    take_with_you: 'Доступ к интернету и документу для работы.',
    contact_person: 'Евгений Валерьевич Кустов',
    is_active: true
  }
];
